spring.application.name=ms-fixtures
server.port = 8085


# Individually hosted
#auth.service.url=http://localhost:8081
#external-api.url=http://localhost:8090

# Docker
auth.service.url=http://ms-auth:8081
external-api.url=http://external-api:8090