spring.application.name=ms-standings
server.port = 8086


# Individually hosted
#auth.service.url=http://localhost:8081
#teams.service.url=http://localhost:8083
#external-api.url=http://localhost:8090

# Docker
auth.service.url=http://ms-auth:8081
teams.service.url=http://ms-teams:8083
external-api.url=http://external-api:8090